name: face_id
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  camera: ^0.10.5+2
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  google_mlkit_commons: ^0.4.0
  google_mlkit_object_detection: ^0.8.0
  logger: ^1.4.0
  path: ^1.8.3
  path_provider: ^2.0.15
  provider: ^6.0.5
  quickalert: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/
